### ISSUE TITLE
Parsers don't understand objects as query parameters

### ISSUE THREAD

**Issue by RonSijm** [MV-GH/lemmy_openapi_spec#11]
Hey there,

I started using your spec to generate a c# client - thanks for making this! I know there are a bunch of existing libraries out there already, but when generating a client, I can customize way more.

Anyways, however I noticed some of the DTOs don't get parsed correctly.

For example

````
  /post/list:
    get:
      tags:
        - Post
      parameters:
        - name: ListPosts
          in: query
          schema:
            $ref: '#/components/schemas/GetPosts'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPostsResponse'
````

This is pretty much the same for other inputs with query parameters

Parsers interpret this as that there is a `ListPosts` query parameter, with an GetPosts object. 

The usual approach is to only add simple types as query parameters

I *think* another solution for this might be to add an `explode: true` - https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameterObject

> When this [explode] is true, parameter values of type array or object generate separate parameters for each value of the array or key-value pair of the map. 

That sounds roughly as what should be happening

**Comment by MV-GH** [comment]
Ah yes indeed, thank you for bringing this to my attention. I'll take a look if the `explode` will solve it. If so I'll make a fix for it

**Comment by MV-GH** [comment]
![image](https://github.com/MV-GH/lemmy_openapi_spec/assets/67873169/d4d1c145-e9a6-4d85-bb58-70ee6a3879bf)

Swagger-UI does seem to properly handle it of the explode property. But I'll add it regardless

**Comment by MV-GH** [comment]
Can you test if the new spec, with the explode property solves your problem?
